image:
  name: cypress/included:6.0.0
  entrypoint: [""]

stages:
  - test

test:
  stage: test
  script:
    - npm i
    - node index.js
  artifacts:
    expire_in: 4 hours
    when: always
    paths:
    - cypress/screenshots
    - cypress/videos

